build:
  maxIssues: 3
  weights:
    ForbiddenComment: 0
    MatchingDeclarationName: 1
    ReturnCount: 0
    TooGenericExceptionCaught: 0
    TooGenericExceptionThrown: 1

style:
  MagicNumber:
    active: false

console-reports:
  active: true
  # exclude:
  #  - 'ProjectStatisticsReport'
  #  - 'ComplexityReport'
  #  - 'NotificationReport'
  #  - 'FindingsReport'
  #  - 'FileBasedFindingsReport'
  #  - 'BuildFailureReport'

processors:
  active: true
  # exclude:
  # - 'FunctionCountProcessor'
  # - 'PropertyCountProcessor'
  # - 'ClassCountProcessor'
  # - 'PackageCountProcessor'
  # - 'KtFileCountProcessor'
